### ISSUE TITLE
OmniMIDI crashes chrome browsers when they try to request midi devices

### ISSUE THREAD

**Issue by Kaydax** [KaleidonKep99/Keppy-s-MIDI-Driver#229] opened 2022-04-10 17:39 UTC
**Problem**
OmniMIDI crashes browsers when the browser request midi devices

**Steps to reproduce**
1. Goto any website that request midi devices
2. It crashes

**Expected behavior**
Not to crash

**Environment**
 - Operating system: Windows 10
 - CPU: Ryzen 7 5800x
 - RAM: 32GB
 - MIDI application: Any chrome browser
 - Version of the driver: 14.6.13

**Comment by KaleidonKep99** [comment] 2022-04-10 17:44
I can't reproduce the issue.
![image](https://user-images.githubusercontent.com/11065274/162632336-1ff4d8c7-2869-489f-9a36-3b83c552fbae.png)

Can you send me the minidump in private?

**Comment by KaleidonKep99** [comment] 2022-09-11 14:15
Forgot to close this, seems to be a bug caused by a broken update on Google's part.

**Closed as completed by KaleidonKep99** 2022-09-11 14:15 UTC
Labels: Bug, BASS library issue, Host application issue
