### ISSUE TITLE
Applications using the synth sometimes crash when closed

### ISSUE THREAD

**Issue by GenericCherrySwitch** [KaleidonKep99/Keppy-s-MIDI-Driver#246] opened 2023-02-01 07:24 UTC
**Problem**
Closing any application while the synth is active (e.g. playing a MIDI) sometimes causes the program to encounter a Guru meditation and the audio either persists for a few moments or immediately halts after the error message appears.

**Steps to reproduce**
1. Play any MIDI on any application that uses OmniMIDI
2. Close the application
3. Error appears

**Expected behavior**
The program closes with no error messages present.

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/44690814/215971067-f20b697e-55dd-4cff-9b72-8499786ed556.png)

**Environment**
 - Operating system: Windows 10 22H2, Build 19045.2486
 - CPU: AMD Ryzen 3 2200G
 - RAM: 16 GB
 - MIDI application: TMIDI (64-bit iirc)
 - Version of the driver: 14.6.14

**Additional context**
N/A

**Comment by KaleidonKep99** [comment] 2023-04-21 22:35
Should be fixed now, it was caused by a bug in BASSMIDI.

Let me know if you still have issues.

**Closed as completed** 2023-06-22 14:05 UTC
Labels: Bug
