### ISSUE TITLE
Unstable audio engine

### ISSUE THREAD

**Issue by kiptunor** [KaleidonKep99/Keppy-s-MIDI-Driver#248] opened 2023-02-09 06:21 UTC
**Problem**
The issue is that some midi apps like UMP or domino are crashing while playing midis and when it happend I always got this error:
![Screenshot 2023-02-09 081010](https://user-images.githubusercontent.com/92180085/217732996-efb3bc21-624e-4b74-92d3-18b2a8e0a9a4.png)

**Steps to reproduce**
1. The MIDI can be found here: https://www.youtube.com/watch?v=0M18B_zyHcU&t=0s&ab_channel=Danidanijr

**Environment**
 - Windows 10 Pro 21H2
CPU: Intel Core i3 12100
RAM: 16gb DDR4 at 3200 MHz 
 - UMP
 - 14.614 (latest)

**Comment by KaleidonKep99** [comment] 2023-04-21 22:36
It should be fixed now. It was caused by a bug in BASSMIDI.

Let me know if you still have issues.

**Closed as completed** 2023-06-22 14:05 UTC
Labels: Bug
